### PR TITLE
[JENKINS-38690] Do not cause a Thread storm in IOHub

### PR DESCRIPTION
**Pull request by stephenc**
Replaces #115

@reviewbybees

All tests pass on my machine.

| "protocol"                         | "io"           | "clients" | "interval" | "payload" | "observedRate" | "expectedRate" | "vmLoad" | "expectedVmLoad" | "threads" | "avgMemory" | "stdMemory" | "dfMemory" | "maxMemory" | "gc[0].name"             | "gc[0].count" | "gc[0].time" | "gc[1].name"  | "gc[1].count" | "gc[1].time" | 
|------------------------------------|----------------|-----------|------------|-----------|----------------|----------------|----------|------------------|-----------|-------------|-------------|------------|-------------|--------------------------|---------------|--------------|---------------|---------------|--------------| 
| "JNLP4-plaintext (this change)"    | "non-blocking" | 100       | 100        | -1        | 1000.0         | 1000.0         | 1.36     | 1.36             | 46        | 191650.05   | 43763.10    | 1981       | 3728384.00  | "PS         MarkSweep"   | 2             | 0.042        | "PS Scavenge" | 935           | 1.47         | 
| "JNLP4-plaintext (from #115)"      | "non-blocking" | 100       | 100        | -1        | 1000.0         | 1000.0         | 1.48     | 1.48             | 60        | 199295.16   | 40312.72    | 1981       | 3728384.00  | "PS           MarkSweep" | 2             | 0.045        | "PS Scavenge" | 885           | 1.509        | 
| "JNLP4-plaintext (current master)" | "non-blocking" | 100       | 100        | -1        | 1000.0         | 1000.0         | 1.53     | 1.53             | 44        | 195592.79   | 43263.94    | 1981       | 3728384.00  | "PS      MarkSweep"      | 2             | 0.041        | "PS Scavenge" | 902           | 1.509        |

### CODE REVIEW

**Comment by stephenc** [comment]
No new findbugs introduced in this change

**Comment by stephenc** [comment]
@oleg-nenashev this is the one we want

**Comment by stephenc** [comment]
:bee: on @jtnord changes

**Comment by jtnord** [comment]
:bee: on @stephenc's changes

**Comment by stephenc** [comment]
@oleg-nenashev we merged so that @kohsuke can cut a remoting 3.0 release safely

**Comment by oleg-nenashev** [comment]
Well, we're in sync with KK on remoting.
I've noticed the team that my Internet connection may be pretty bad on these days, hence I do not see why a community review process has been overridden by a "not-so-strict" CloudBees one.

**Comment by oleg-nenashev** [comment]
I decided to delay the remoting 3 release for 1 week since I do not feel comfortable about releasing it without additional soak testing

**Comment by oleg-nenashev** [comment]
The test instance with the deployed remoting looks good so far

**Pull request merged**
