### PR TITLE
[JENKINS-68542] [WebSocket] Capture cookie returned by server and reuse for reconnection attempts

### PR DESCRIPTION
**Pull request by Vlatombe**
[JENKINS-68542](https://issues.jenkins.io/browse/JENKINS-68542)

Cherry-picked from cc32c3b (#537)

Remoting 4.13 is the version pinned on Jenkins LTS [2.332](https://github.com/jenkinsci/jenkins/blob/stable-2.332/pom.xml#L93) and [2.346](https://github.com/jenkinsci/jenkins/blob/stable-2.346/pom.xml#L93)

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by Vlatombe** [comment]
I guess I'll need `trusted.ci.jenkins.io` (cf #532) for this release.

**Comment by MarkEWaite** [comment]
> I guess I'll need `trusted.ci.jenkins.io` (cf #532) for this release.

I thought that the transition to JEP-229 was complete enough on this repository that a new release will be created once the pull request is merged.

The only case that I know for generating the release on trusted.ci.jenkins.io is if we require a signed jar file.  Is a signed jar file required with this change?

I have permission to launch releases of remoting on trusted.ci.jenkins.io, if needed.

**Comment by Vlatombe** [comment]
@MarkEWaite this is a case for a backport on a version predating signature removal and JEP-229 setup.

**Comment by MarkEWaite** [comment]
> @MarkEWaite this is a case for a backport on a version predating signature removal and JEP-229 setup.

Thanks @Vlatombe .  I had missed that the destination branch is a backport.

Once it is merged, I believe that I can launch the build of the backport.

**Comment by Vlatombe** [comment]
Unsure what is going on with the windows build though...

**Comment by Vlatombe** [comment]
#540

**Comment by Vlatombe** [comment]
@MarkEWaite `stable-4.13.x` is ready for release (4.13.1). Thank you!

**Pull request merged**
