### PR TITLE
[JENKINS-26759] Add more tests for FileSystemJarCache

### PR DESCRIPTION
**Pull request by akshayabd**

### CODE REVIEW

**Comment by akshayabd** [comment]
@jglick plz review

**Comment by oleg-nenashev** [comment]
Looks good to me

**Comment by akshayabd** [comment]
Thanks for reviewing - once this is merged in I think we can mark JENKINS-26759 as fixed

**Comment by oleg-nenashev** [comment]
Merged, thanks for the improvement

**Pull request merged**
