### PR TITLE
[INFRA-1248] - Temporarily disable the Windows build till the INFRA issue is fixed

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/INFRA-1248, just a workaround

@reviewbybees @jtnord

### CODE REVIEW

**Comment by jglick** [comment]
FTR

    Failed to execute goal org.codehaus.mojo:build-helper-maven-plugin:1.7:regex-property (version-property) on project remoting: Execution version-property of goal org.codehaus.mojo:build-helper-maven-plugin:1.7:regex-property failed: Illegal group reference

**Comment by jglick** [comment]
```xml
<replacement>-SNAPSHOT (${build.type}-${now}-${user.name})</replacement>
```

Seems like `build-helper-maven-plugin` does not support a `literalReplacement` parameter, so we would either need to use some other plugin (Groovy, say), or patch that plugin, or drop this feature. Same for Jenkins core I suppose.

**Comment by jglick** [comment]
```sh
mvn -Duser.name='big$money' validate -e
```

produces

```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at org.codehaus.mojo.buildhelper.RegexPropertyMojo.execute(RegexPropertyMojo.java:126)
	at …
```

**Comment by oleg-nenashev** [comment]
Closing in favor of #173

**Pull request closed without merging**
