### PR TITLE
[FIX JENKINS-40710] Match headers case-insensitively

### PR DESCRIPTION
**Pull request by daniel-beck**
Untested (tests seem broken for me).

[JENKINS-40710](https://issues.jenkins-ci.org/browse/JENKINS-40710)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It's likely a wider issue, because we match connection headers in a case-sensitive mode in other places. But 🐝 for this particular change

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
Merging towards 3.5

**Comment by cgag** [comment]
I found a few problems in this fix and submitted a PR here:  https://github.com/jenkinsci/remoting/pull/140

**Pull request merged**
