### PR TITLE
[JENKINS-55976] - Add missing log call

### PR DESCRIPTION
**Pull request by amuniz**
A log record was created but never logged.

/cc @oleg-nenashev

### CODE REVIEW

**Comment by amuniz** [comment]
Done. [JENKINS-55976](https://issues.jenkins-ci.org/browse/JENKINS-55976)

**Comment by oleg-nenashev** [comment]
thanks!

**Comment by jeffret-b** [comment]
Released as Remoting 3.29. Do we want to open a PR to include this version in core?

**Comment by oleg-nenashev** [comment]
yes, it would be nice

**Comment by jeffret-b** [comment]
Submitted PR to pull the new version into Jenkins: jenkinsci/jenkins#3887

**Pull request merged**
