### PR TITLE
[JENKINS-46341] - Fix Unix PR Builder

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] - In WorkDir Tests verify that the R/W/X flags can be really set
- [x] - Skip tests of obsolete protocols in the PR builder (JNLP NIO tests are flaky)
- [ ] - The common PR build should run all tests
- [ ] - Provide reference Docker image for testing Remoting

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It's going to fail even now

**Comment by oleg-nenashev** [comment]
It started working without this patch due to whatever reason

**Comment by jeffret-b** [comment]
@oleg-nenashev, is there any need to keep this PR open? It seems to have been superseded by a number of events since it was opened.

**Comment by jeffret-b** [comment]
No response and it doesn't look current.

**Pull request closed without merging**
