### PR TITLE
Update the url of HudsonArch-Remoting.pdf

### PR DESCRIPTION
**Pull request by donhui**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Update the url of HudsonArch-Remoting.pdf, because hudson-ci.org cannot be accessed.

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1 for the update itself. At the same time the slidedeck is quite old. While still useful for the `JNLP4-connect` protocol and Jenkins RMI parts, it does not represent newer connection modes (websockets, Remoting over Apache Kafka). It also uses the deprecated terminology. Ideally we should replace the document by a more modern architecture overview.

I have an old https://speakerdeck.com/onenashev/day-of-jenkins-2017-dealing-with-agent-connectivity-issues slidedeck with some architecture references. We also made a "Scaling Network Connections from the Jenkins controller" talk together with @jglick  with some insight([video](https://www.youtube.com/watch?v=h7JK6Ak3cJc)). These talks do not really qualify as architecture overview replacing this old deck

**Comment by donhui** [comment]
@oleg-nenashev The slide and video you mentioned are very useful for one who want to know more about remoting.  It is really great!

**Review by jglick — APPROVED** [review]
The middle section is indeed specific to TCP transport. OTOH the WebSocket transport is conceptually much simpler (there is not a lot to say about it), and the beginning and final sections are independent of transport and remain valid descriptions.

**Comment by oleg-nenashev** [comment]
Thanks for the patch @donhui ! Any contributions are welcome and much appreciated. I will try to spend some time and to add materials I know about

**Pull request merged**
