### PR TITLE
[JENKINS-38696] Fix the failing unit tests on Linux and windows.

### PR DESCRIPTION
**Pull request by jtnord**
The unit tests are failing for several months on Linux
(https://ci.jenkins.io/job/Core_Folder/job/remoting/) and fail on windows.

This fixes that so that the build is blue again.

@reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
Looks good to me :+1: 
Maybe you want to remove everything under `src/main/java` also?

**Comment by oleg-nenashev** [comment]
Hmm....
@jtnord Are you sure we want to do it?

**Comment by jtnord** [comment]
@oleg-nenashev I'm open to alternate implementations :-P

**Comment by oleg-nenashev** [comment]
@jtnord Merge conflict. I also have no idea why you want to delete 15k codelines of tests. Likely it was just a temporary patch to remove passing tests from the scope

**Comment by jtnord** [comment]
@oleg-nenashev it removed all tests - so that all tests would pass on windows :-p

**Comment by oleg-nenashev** [comment]
I consider merging it on April 1st

**Comment by oleg-nenashev** [comment]
I missed April 1st, and it is too long to wait till the next one.
@jtnord Good news for you. My HW code signing certificate works on Windows only, so I will have to fix tests there if I want to release the stuff without `-DskipTests`.

**Comment by jtnord** [comment]
@oleg-nenashev good luck!

:four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover::four_leaf_clover:

**Comment by amuniz** [comment]
@oleg-nenashev It took you a while to notice the branch name `JENKINS-38696-joke` 😄

**Comment by oleg-nenashev** [comment]
@amuniz I noticed it starting from the very first comment :P

**Pull request closed without merging**
