### PR TITLE
[JENKINS-65873] [JENKINS-68954] Optimize `AnonymousClassWarnings` (#559)

### PR DESCRIPTION
**Pull request by NotMyFault**
(cherry picked from commit b940aae4f72e9cc72fee5435ffcdd6f0706fe3a9)

Integrating as per request into the stable branch of remoting for 2.346.3

### CODE REVIEW

**Comment by NotMyFault** [comment]
cc @timja or @basil, no merge permissions here.

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
Thanks!

**Comment by NotMyFault** [comment]
Btw, is there a dedicated release job on release.ci covering the target branch? https://release.ci.jenkins.io/job/components/job/remoting/ covers master only.

**Comment by timja** [comment]
Remoting is released via CD on master in this repo.

On release.ci.jenkins.io the remoting job releases the 4.13.x branch,

see the config here:
https://github.com/jenkins-infra/release/blob/master/profile.d/components/remoting

**Comment by NotMyFault** [comment]
> On release.ci.jenkins.io the remoting job releases the 4.13.x branch,

Oic, the build log confirms that, though weird to have it named master.

**Pull request merged**
