### PR TITLE
JENKINS-22932

### PR DESCRIPTION
**Pull request by kohsuke**
Improving diagnostics.

### CODE REVIEW

**Comment by kohsuke** [comment]
@reviewbybees

**Comment by christ66** [comment]
:+1:

**Comment by rsandell** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
LGTM. Probably, it also makes sense to throw the assertion error from <code>finally</code> block and document it in Javadoc

**Comment by jtnord** [comment]
:+1:

**Comment by stephenc** [comment]
:+1:

**Pull request merged**
