### PR TITLE
Bump to latest jenkinsci/pom

### PR DESCRIPTION
**Pull request by batmat**
Downstream to https://github.com/jenkinsci/pom/pull/16

@reviewbybees

### CODE REVIEW

**Comment by batmat** [comment]
WUT. IIUC the build fails because the pom can't be found, but this succeeded with the exact same value for https://github.com/jenkinsci/maven-interceptors/pull/14, on the same infra. Possibly some temporary flakiness, going to retrigger the build to see if the error is persistent.

**Comment by batmat** [comment]
@oleg-nenashev this fails because the pom SNAPSHOT cannot be found, but it works on https://github.com/jenkinsci/maven-interceptors/pull/14 

I'm probably missing something obvious, like a typo or so, if you can throw a quick look would be great. Thanks

**Comment by oleg-nenashev** [comment]
@batmat it looks fine. Maybe there is a special symbol or something. Anyway, I am fine with the upstream release since the build is passing

**Comment by oleg-nenashev** [comment]
This change does not make the things worse

**Pull request merged**
