### PR TITLE
[JENKINS-37565] - Really allow compiling with Java 7

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just a leftover fix

@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by jglick** [comment]
:bee: though should this not be picked up automatically from the parent POM when you set the right `java.level`?

**Comment by oleg-nenashev** [comment]
> though should this not be picked up automatically from the parent POM when you set the right java.level?

It should, but https://github.com/jenkinsci/pom/blob/master/pom.xml does not include Animal Sniffer at all. Maybe needs a fix

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
