### PR TITLE
[NO_MERGE][JENKINS-23271] - Allow exporting objects with disabled automatic unexporting

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Particular remoting calls may cause asynchronous operations on Jenkins agents.

E.g. RemoteProcess, which is being created by hudson.Launcher. In such case we export object of the remote process in the ExportTable, and then create an invocation handler, which is being serialized back to the master. After that the local instance of the wrapped object is not being used anymore, hence it can be garbage collected along with the exported object instance. This garbage collection causes unexported of the object.

According to my experiments, on Java8 such garbage collection of RemoteInvocationHandler frequently happens between <code>RemoteProсess#start()</code> and <code>RemoteProcess#join()</code> calls when running many short operations on the agent (e.g. sh steps), which leads to JENKINS-23271.

So I decided to introduce new API, which prohibits automatic unexport for such async calls. It should be mostly safe since RemoteProcess calls commonly end automatically or get terminated by external side. But additional feedback would be appreciated.

https://issues.jenkins-ci.org/browse/JENKINS-23271

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Bug investigation braindump is here: https://docs.google.com/document/d/1nu7jD2bNqEzD7kOM1R0VUpExycPNUq8wOTTLrr9xvOY/edit

**Comment by stephenc** [comment]
no tests?

**Comment by feiniao0308** [comment]
When will this change submit? I'm waiting for it :-). Thanks!

**Comment by oleg-nenashev** [comment]
@feiniao0308 This change is not going to fly in such way. It works, but actually it just suppresses the root cause of the problem with Garbage collector.
I'm going to propose another fix later.

**Comment by feiniao0308** [comment]
@oleg-nenashev Thanks a lot, then i'll wait for the fix :-)

**Comment by jglick** [comment]
> I'm going to propose another fix later.

So, should this PR be marked a werk-in-progress (or even closed)?

**Comment by oleg-nenashev** [comment]
@jglick sorry, fixed

**Comment by feiniao0308** [comment]
When will another fix came out?

**Comment by oleg-nenashev** [comment]
When I find time to fix it :(

**Comment by oleg-nenashev** [comment]
Closing in favor of https://github.com/jenkinsci/jenkins/pull/2635

**Pull request closed without merging**
