### PR TITLE
No more `@IgnoreJRERequirement`s

### PR DESCRIPTION
**Pull request by jglick**
A bit of cleanup started in #442 but not completed.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Review by basil — APPROVED** [review]

**Review by jeffret-b — APPROVED** [review]

**Comment by jeffret-b** [comment]
I have no idea what's going on with the CI builds. It used to work.

**Comment by MarkEWaite** [comment]
> I have no idea what's going on with the CI builds. It used to work.

The message is "error starting fork" and then the test enter a timeout.  I assume the available memory on the agent has changed since the switch to using `maven` agents provided by Kubernetes instead of using Azure Container Instances.  Is there an easy way to deduce if memory pressure or inadequate processor resources are causing the failure to fork?

**Comment by jeffret-b** [comment]
Not that I'm aware of. Probably memory I would guess but I don't have
anything to go on. Those forking tests are kind of weird but they do cover
important code paths.

**Comment by jglick** [comment]
> Probably memory I would guess

Also noted [here](https://issues.jenkins.io/browse/JENKINS-61212?focusedCommentId=413224&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413224).

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
> > Probably memory I would guess
> 
> Also noted [here](https://issues.jenkins.io/browse/JENKINS-61212?focusedCommentId=413224&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-413224).

looks fixed now

**Pull request merged**
