### PR TITLE
[FIXED JENKINS-31510]

### PR DESCRIPTION
**Pull request by kohsuke**
Reworked PR #64 based on the tip.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Retriggering the CI. Seems it does not work due to the remoting layer

**Comment by oleg-nenashev** [comment]
There are many usages in the Jenkins core and plugins:
https://github.com/search?p=5&q=user%3Ajenkinsci+%22org.apache.commons.fileupload%22&ref=searchresults&type=Code&utf8=✓

After a random check I have not found it's propagation over the channel, but seems a full review is required

**Comment by kohsuke** [comment]
Note that we already uses patched commons-fileupload that is not serializable. I think this is a no-brainer change that can be just merged.

**Comment by oleg-nenashev** [comment]
Looking into the commons-fileupload 's code

**Comment by kohsuke** [comment]
I don't remember much about this PR but JENKINS-31510 is already marked as fixed.

**Pull request closed without merging**
