### PR TITLE
[JENKINS-37565] - Upgrade source level to Java 7

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change does not update the code to the Java7 style, but we will do it later. It requires https://github.com/jenkinsci/pom/pull/11

### CODE REVIEW

**Comment by jglick** [comment]
You need to `deploy` the snapshot.

**Comment by jglick** [comment]
:bee: if that is done (though upstream I suggested `7` be the default, so merely updating the parent would suffice)

**Comment by oleg-nenashev** [comment]
@jglick No. I need reviews of https://github.com/jenkinsci/pom/pull/11 ;)

**Comment by oleg-nenashev** [comment]
@reviewbybees ready to go forward

**Pull request merged**
