### PR TITLE
ProxyException should also retain any suppressed exceptions from the original

### PR DESCRIPTION
**Pull request by jglick**
Potentially relevant for Pipeline, especially after https://github.com/jenkinsci/workflow-api-plugin/pull/18.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
🐝

**Comment by jglick** [comment]
Hmm, the `ci.jenkins.io` build seems badly broken.

Anyway, @reviewbybees done

**Comment by oleg-nenashev** [comment]
@jglick Any need to backport it to 2.x?

**Comment by jglick** [comment]
> Any need to backport it to 2.x?

No, it is just something I happened to notice and decided to fix—I am not waiting on it.

**Pull request merged**
